version: 0.1

phases:

  install:
    commands:
      - npm install firebase
      - npm i --save-dev expose-loader
      - npm i --save jquery
      - npm install vue-iamport
      - yarn install

